### ISSUE TITLE
Per-repository Prefect configuration

### ISSUE THREAD

**Issue by PathogenDavid** [bonsai-rx/prefect#16]
(I don't know that this is *strictly* necessary, but wanted to document the two approaches I've considered for doing this.)

Right now any per-repository exceptions made for Prefect are hard-coded within Prefect itself.

This is mostly fine for use of Prefect within the Bonsai foundation, but it's super flexible. It could be desirable to be able to specify parameters to specific rules on a per-repository basis.

This configuration could be stored within the repository itself, or might be part of some repo set configuration file.

For the latter, instead of specifying a repo set to Prefect using something like `prefect C:\Projects\bonsai-rx\` you would specify a file `prefect C:\Projects\bonsai-rx.yml` which might look something like:

```
# Listed keys are simply repositories to be loaded
arduino:
daqmx:
aruco:

# Repo with rule-specific configuration
machinelearning:
  CSharpProjectsInSrcRule:
    AllowTestsFolder: true

# Repo with ignored external dependency
spikeglx:
  ignore:
    # External dependency
    - 'modules/**'

# Repo with file thats that would normally violate rules
tld:
  ignore:
    # Legacy C++ package
    - '*.nuspec'

# Theoretical package which cannot have its name automatically detected
whatever:
  project-name: 'Bonsai.Whatever'
```

For the former, a `.prefect` file in the repo root (or some other well-known path) would define the configuration (similar to above, just for a single repo.)
